require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const Plant = require('./models/Plant');
const Admin = require('./models/Admin');

const u = (id) => `https://images.unsplash.com/photo-${id}?w=600&q=80`;

const allPlants = [
  // ===== फलदार पौधे (Fruit Plants) =====
  { nameHindi: 'अमरूद', nameEnglish: 'Guava', category: 'Fruit Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Sweet and nutritious guava plant. Grows well in Indian climate with minimal care.' },
  { nameHindi: 'आम', nameEnglish: 'Mango', category: 'Fruit Plants', price: 349, stockStatus: 'in-stock', featured: true, bestseller: true, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'High-quality mango sapling. Produces sweet and juicy mangoes. A must-have for every garden.' },
  { nameHindi: 'नींबू कलमी', nameEnglish: 'Grafted Lemon', category: 'Fruit Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Grafted lemon plant that fruits earlier. Produces large juicy lemons throughout the year.' },
  { nameHindi: 'नींबू देसी', nameEnglish: 'Desi Lemon', category: 'Fruit Plants', price: 179, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Traditional desi lemon variety. Known for its authentic flavor and strong aroma.' },
  { nameHindi: 'संतरा', nameEnglish: 'Orange', category: 'Fruit Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Sweet orange plant. Produces delicious vitamin-rich fruits perfect for fresh juice.' },
  { nameHindi: 'मौसमी', nameEnglish: 'Sweet Lime (Mosambi)', category: 'Fruit Plants', price: 279, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Refreshing sweet lime plant. Bears fruits that are perfect for healthy juices.' },
  { nameHindi: 'फालसा', nameEnglish: 'Phalsa', category: 'Fruit Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: true, image: u('1523348837708-15d4a09cfac2'), description: 'Traditional Indian fruit plant. Produces small purple berries with unique sweet-tart flavor.' },
  { nameHindi: 'चीकू', nameEnglish: 'Sapodilla (Sapota)', category: 'Fruit Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Delicious sapota plant. Bears sweet brown fruits with grainy texture loved by all.' },
  { nameHindi: 'नाशपाती', nameEnglish: 'Pear', category: 'Fruit Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Juicy pear plant. Produces sweet succulent pears perfect for fresh eating.' },
  { nameHindi: 'पपीता', nameEnglish: 'Papaya', category: 'Fruit Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Fast-growing papaya plant. Bears large sweet fruits rich in vitamins and enzymes.' },
  { nameHindi: 'अंगूर', nameEnglish: 'Grapes', category: 'Fruit Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Grape vine plant. Produces sweet juicy grapes perfect for fresh consumption.' },
  { nameHindi: 'लीची', nameEnglish: 'Litchi', category: 'Fruit Plants', price: 399, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Premium litchi plant. Bears juicy sweet lychees with delightful flavor and aroma.' },
  { nameHindi: 'कटहल', nameEnglish: 'Jackfruit', category: 'Fruit Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Versatile jackfruit plant. Produces the largest tree fruit, delicious when ripe or raw.' },
  { nameHindi: 'बेर', nameEnglish: 'Indian Jujube', category: 'Fruit Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Hardy ber plant. Produces tangy-sweet fruits rich in vitamin C and minerals.' },
  { nameHindi: 'बेलपत्र', nameEnglish: 'Bael (Wood Apple)', category: 'Fruit Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Sacred bel plant with medicinal value. Fruits make a refreshing traditional drink.' },
  { nameHindi: 'आँवला', nameEnglish: 'Indian Gooseberry', category: 'Fruit Plants', price: 179, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Powerful amla plant. Vitamin C rich fruits used in traditional medicine and pickles.' },
  { nameHindi: 'शरीफा', nameEnglish: 'Custard Apple', category: 'Fruit Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Sweet custard apple plant. Produces creamy delicious fruits with natural sweetness.' },
  { nameHindi: 'जामुन', nameEnglish: 'Java Plum (Black Plum)', category: 'Fruit Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Medicinal jamun plant. Produces purple-black fruits known for blood sugar control.' },

  // ===== फूलदार पौधे (Flowering Plants) =====
  { nameHindi: 'गुड़हल लाल', nameEnglish: 'Red Hibiscus', category: 'Flowering Plants', price: 99, stockStatus: 'in-stock', featured: true, bestseller: true, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Stunning red hibiscus plant. Large vibrant flowers bloom throughout the year.' },
  { nameHindi: 'गुड़हल पीला', nameEnglish: 'Yellow Hibiscus', category: 'Flowering Plants', price: 99, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Beautiful yellow hibiscus. Bright sunny blooms add color to any garden.' },
  { nameHindi: 'गुड़हल सफेद', nameEnglish: 'White Hibiscus', category: 'Flowering Plants', price: 99, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Elegant white hibiscus plant. Pure white flowers create a serene garden atmosphere.' },
  { nameHindi: 'गुलाब', nameEnglish: 'Rose', category: 'Flowering Plants', price: 199, stockStatus: 'in-stock', featured: true, bestseller: true, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Beautiful flowering plant with fragrant blooms. Available in multiple colors.' },
  { nameHindi: 'चाँदनी', nameEnglish: 'Crape Jasmine', category: 'Flowering Plants', price: 129, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Fragrant chandni plant. White star-shaped flowers with enchanting evening fragrance.' },
  { nameHindi: 'बेला', nameEnglish: 'Arabian Jasmine', category: 'Flowering Plants', price: 79, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Intensely fragrant bela jasmine. Small white flowers with captivating sweet scent.' },
  { nameHindi: 'बोगनवेलिया', nameEnglish: 'Bougainvillea', category: 'Flowering Plants', price: 299, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Colorful flowering vine perfect for gardens and walls. Drought resistant and vibrant.' },
  { nameHindi: 'अडेनियम', nameEnglish: 'Desert Rose', category: 'Flowering Plants', price: 449, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: true, image: u('1518531933037-91b2f5f229cc'), description: 'Exotic desert rose with striking pink blooms and unique swollen stem. Perfect pot plant.' },
  { nameHindi: 'रातरानी', nameEnglish: 'Night Blooming Jasmine', category: 'Flowering Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Enchanting raatrani plant. Small flowers release heavenly fragrance at night.' },
  { nameHindi: 'इक्सोरा', nameEnglish: 'Ixora', category: 'Flowering Plants', price: 129, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Colorful ixora plant with dense clusters of bright red-orange flowers.' },
  { nameHindi: 'हरसिंगार', nameEnglish: 'Parijat (Night-flowering Jasmine)', category: 'Flowering Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Divine parijat plant. Orange-stemmed white flowers that fall at dawn, spreading fragrance.' },
  { nameHindi: 'टिकोमा', nameEnglish: 'Tecoma', category: 'Flowering Plants', price: 179, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Vibrant tecoma plant with trumpet-shaped yellow or orange flowers. Attracts butterflies.' },
  { nameHindi: 'कैलेंड्रा', nameEnglish: 'Calliandra (Powder Puff)', category: 'Flowering Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: true, image: u('1530092285049-1c42085fd395'), description: 'Unique powder puff plant with fluffy red flowers. A beautiful ornamental shrub.' },

  // ===== शोभादार पौधे (Ornamental / Decorative Plants) =====
  { nameHindi: 'फाइकस काला', nameEnglish: 'Black Ficus', category: 'Decorative Plants', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Elegant black ficus with dark glossy leaves. A sophisticated ornamental plant.' },
  { nameHindi: 'फाइकस पीला', nameEnglish: 'Golden Ficus', category: 'Decorative Plants', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Beautiful golden ficus with bright yellow-green variegated leaves.' },
  { nameHindi: 'फाइकस स्टार लाइट', nameEnglish: 'Ficus Starlight', category: 'Decorative Plants', price: 399, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Stunning ficus starlight with white and green variegated foliage.' },
  { nameHindi: 'मोरपंखी', nameEnglish: 'Thuja (Morpankhi)', category: 'Decorative Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Feathery morpankhi plant resembling peacock feathers. Perfect for hedges and borders.' },
  { nameHindi: 'जूनीपर्स', nameEnglish: 'Juniper', category: 'Decorative Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Hardy juniper plant with aromatic needle-like foliage. Great for landscaping.' },
  { nameHindi: 'बॉटल पाम', nameEnglish: 'Bottle Palm', category: 'Decorative Plants', price: 599, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: true, image: u('1518531933037-91b2f5f229cc'), description: 'Unique bottle-shaped palm. A stunning focal point for gardens and entrances.' },
  { nameHindi: 'मछली पाम', nameEnglish: 'Fish Tail Palm', category: 'Decorative Plants', price: 499, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Exotic fishtail palm with distinctive leaf shape. Adds tropical feel to any space.' },
  { nameHindi: 'एरेका पाम', nameEnglish: 'Areca Palm', category: 'Decorative Plants', price: 399, stockStatus: 'in-stock', featured: true, bestseller: true, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Popular indoor palm known for air purification. Graceful fronds create tropical ambiance.' },
  { nameHindi: 'पाम की सभी वैरायटी', nameEnglish: 'Palm Varieties', category: 'Decorative Plants', price: 499, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Wide selection of premium palm varieties to enhance your garden landscape.' },
  { nameHindi: 'ड्रासीना', nameEnglish: 'Dracaena', category: 'Decorative Plants', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Low-maintenance dracaena with striking foliage patterns. Perfect for indoor decor.' },
  { nameHindi: 'चन्दन', nameEnglish: 'Sandalwood', category: 'Decorative Plants', price: 799, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Precious sandalwood sapling. Known for its fragrant heartwood and medicinal value.' },
  { nameHindi: 'गोल्डन बॉटल ब्रश', nameEnglish: 'Golden Bottle Brush', category: 'Decorative Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Unique golden bottle brush plant with striking flower spikes. Attracts birds and bees.' },
  { nameHindi: 'यूका', nameEnglish: 'Yucca', category: 'Decorative Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Architectural yucca plant with spiky leaves. Drought tolerant and low maintenance.' },
  { nameHindi: 'रैविश पाम', nameEnglish: 'Ravenea Palm', category: 'Decorative Plants', price: 449, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Elegant ravenea palm with graceful arching fronds. Great indoor or outdoor plant.' },
  { nameHindi: 'एरोकेरिया', nameEnglish: 'Araucaria', category: 'Decorative Plants', price: 549, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Beautiful araucaria with symmetrical branches. Adds a formal touch to landscapes.' },
  { nameHindi: 'फोनिक्स पाम', nameEnglish: 'Phoenix Palm', category: 'Decorative Plants', price: 599, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Majestic phoenix palm with feathery fronds. Creates dramatic garden presence.' },
  { nameHindi: 'लोलीना पाम', nameEnglish: 'Livistona Palm', category: 'Decorative Plants', price: 499, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Beautiful livistona palm with fan-shaped leaves. Excellent shade-giving ornamental palm.' },
  { nameHindi: 'फरेशेरिया', nameEnglish: 'Fraseria', category: 'Decorative Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Attractive fraseria plant with lush green foliage. Great for garden borders.' },
  { nameHindi: 'विक्टोरिया', nameEnglish: 'Victoria Plant', category: 'Decorative Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Beautiful victoria plant with ornamental foliage. Adds tropical charm to gardens.' },
  { nameHindi: 'सपलेरा', nameEnglish: 'Schefflera', category: 'Decorative Plants', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Umbrella-shaped schefflera plant. Lush green foliage perfect for indoor decoration.' },
  { nameHindi: 'सन ऑफ इंडिया', nameEnglish: 'Song of India', category: 'Decorative Plants', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Vibrant yellow-green variegated plant. Cheerful foliage brightens any space.' },
  { nameHindi: 'इफन बेचीया', nameEnglish: 'Dieffenbachia', category: 'Decorative Plants', price: 279, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Stunning dieffenbachia with large patterned leaves. A classic indoor ornamental plant.' },
  { nameHindi: 'चायना ऑरेंज', nameEnglish: 'China Orange', category: 'Decorative Plants', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Attractive china orange plant with bright orange fruits. Perfect pot plant for decor.' },
  { nameHindi: 'चाँदनी चायना', nameEnglish: 'China Chandni', category: 'Decorative Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Beautiful china chandni variety. White flowers with pleasant fragrance.' },
  { nameHindi: 'साइकस पाम', nameEnglish: 'Cycas Palm', category: 'Decorative Plants', price: 699, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Ancient cycas palm with striking architectural form. A living fossil for your garden.' },
  { nameHindi: 'सी फिडिया', nameEnglish: 'Cifidia', category: 'Decorative Plants', price: 179, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Beautiful ornamental plant with attractive foliage. Ideal for garden beds and pots.' },
  { nameHindi: 'क्रोटन', nameEnglish: 'Croton', category: 'Decorative Plants', price: 199, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Vibrant croton with multicolored leaves. A splash of yellow, red and green for your garden.' },

  // ===== छायादार पौधे (Shade Trees) =====
  { nameHindi: 'अलिस्टोनिया', nameEnglish: 'Alstonia Scholaris', category: 'Shade Trees', price: 399, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Tall shade tree with glossy leaves. Also known as Saptaparni for its leaf clusters.' },
  { nameHindi: 'कदम (कल्पवृक्ष)', nameEnglish: 'Kadam Tree', category: 'Shade Trees', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Sacred kadam tree with fragrant orange flowers. Provides excellent shade and beauty.' },
  { nameHindi: 'अर्जुन', nameEnglish: 'Arjun Tree', category: 'Shade Trees', price: 399, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Medicinal arjun tree known for its heart-healthy bark. A valuable shade tree.' },
  { nameHindi: 'कचनार', nameEnglish: 'Orchid Tree', category: 'Shade Trees', price: 449, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Stunning kachnar tree with beautiful orchid-like flowers. Edible buds are also used in cooking.' },
  { nameHindi: 'कनेर', nameEnglish: 'Oleander', category: 'Shade Trees', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Evergreen kaner shrub with pink or white flowers. Hardy and drought tolerant.' },
  { nameHindi: 'चक्रेशिया', nameEnglish: 'Chakresia', category: 'Shade Trees', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Fast-growing shade tree with dense foliage. Ideal for creating natural canopy.' },
  { nameHindi: 'बालमखीरा', nameEnglish: 'Balam Kheera Tree', category: 'Shade Trees', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Traditional Indian tree with medicinal properties. Provides good shade coverage.' },
  { nameHindi: 'पीपल', nameEnglish: 'Sacred Fig', category: 'Shade Trees', price: 399, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Sacred tree with heart-shaped leaves. Grows into a large shade-giving tree.' },
  { nameHindi: 'पाकड़', nameEnglish: 'White Fig', category: 'Shade Trees', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Large pakad tree with spreading canopy. Excellent shade provider for gardens.' },
  { nameHindi: 'कनकचम्पा', nameEnglish: 'Golden Champa', category: 'Shade Trees', price: 499, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Fragrant golden champa tree with stunning yellow flowers. Enchanting garden addition.' },
  { nameHindi: 'लजिस्टोनिया', nameEnglish: 'Livistona', category: 'Shade Trees', price: 449, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Majestic livistona palm with large fan-shaped leaves. Creates tropical ambiance.' },
  { nameHindi: 'पुत्रजीवा', nameEnglish: 'Putranjiva Tree', category: 'Shade Trees', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Evergreen putranjiva tree with dense foliage. Known as a child-life giver in tradition.' },
  { nameHindi: 'सेमल', nameEnglish: 'Silk Cotton Tree', category: 'Shade Trees', price: 449, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Impressive semal tree with red flowers and cotton-filled pods. A majestic shade tree.' },
  { nameHindi: 'नीम', nameEnglish: 'Neem', category: 'Shade Trees', price: 249, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Medicinal neem tree with antibacterial properties. Used in traditional medicine.' },
  { nameHindi: 'बकैन', nameEnglish: 'Persian Lilac', category: 'Shade Trees', price: 299, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Fast-growing bakain tree with lilac flowers. Provides light shade and cooling effect.' },
  { nameHindi: 'यूकेलिप्टस', nameEnglish: 'Eucalyptus', category: 'Shade Trees', price: 199, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Aromatic eucalyptus tree. Known for its medicinal scent and rapid growth.' },
  { nameHindi: 'सागौन', nameEnglish: 'Teak', category: 'Shade Trees', price: 599, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1530092285049-1c42085fd395'), description: 'Premium teak sapling. Highly valued for timber. A long-term investment tree.' },
  { nameHindi: 'शीशम', nameEnglish: 'Indian Rosewood', category: 'Shade Trees', price: 449, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1519389950473-47ba0277781c'), description: 'Beautiful sheesham tree with dense shade. Prized for its timber and elegant form.' },
  { nameHindi: 'अमलतास', nameEnglish: 'Golden Shower Tree', category: 'Shade Trees', price: 399, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1530836369250-ef72a3f5cda8'), description: 'Spectacular amaltas tree with cascading golden flowers. A stunning summer bloomer.' },
  { nameHindi: 'गुलमोहर', nameEnglish: 'Gulmohar', category: 'Shade Trees', price: 449, stockStatus: 'in-stock', featured: true, bestseller: false, newArrival: false, image: u('1501004318641-b39e6451bec6'), description: 'Magnificent gulmohar with fiery red-orange flowers. One of the most beautiful flowering trees.' },
  { nameHindi: 'जामुन', nameEnglish: 'Java Plum', category: 'Shade Trees', price: 249, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1416879595882-3373a0480b5b'), description: 'Medicinal jamun tree with purple-black fruits. Known for blood sugar management benefits.' },
  { nameHindi: 'तून', nameEnglish: 'Toon Tree (Red Cedar)', category: 'Shade Trees', price: 349, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1584589167171-541ce45f1eea'), description: 'Fast-growing toon tree with timber. Provides good shade and has medicinal bark.' },

  // ===== हेज (Hedge Plants) =====
  { nameHindi: 'एनर्मी', nameEnglish: 'Duranta', category: 'Hedge Plants', price: 129, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1518531933037-91b2f5f229cc'), description: 'Dense duranta hedge plant with small purple flowers. Perfect for garden boundaries.' },
  { nameHindi: 'गोल्डन डुरांटा', nameEnglish: 'Golden Duranta', category: 'Hedge Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1485955900006-10f4d324d411'), description: 'Vibrant golden duranta with bright yellow foliage. Adds color to hedges and borders.' },
  { nameHindi: 'मेहंदी', nameEnglish: 'Henna', category: 'Hedge Plants', price: 99, stockStatus: 'in-stock', featured: false, bestseller: true, newArrival: false, image: u('1463320726281-696a485928c7'), description: 'Fragrant mehndi plant. Leaves used for natural henna. Makes a beautiful hedge.' },
  { nameHindi: 'कोपिया', nameEnglish: 'Copia', category: 'Hedge Plants', price: 149, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1523348837708-15d4a09cfac2'), description: 'Dense copia hedge plant. Ideal for creating privacy screens and garden borders.' },
  { nameHindi: 'लन्टेना', nameEnglish: 'Lantana', category: 'Hedge Plants', price: 99, stockStatus: 'in-stock', featured: false, bestseller: false, newArrival: false, image: u('1585320806297-9794b3e4eeae'), description: 'Colorful lantana with multicolored flower clusters. Hardy and fast-growing hedge plant.' },
];

const seedDB = async () => {
  try {
    await connectDB();
    await Plant.deleteMany({});
    await Plant.insertMany(allPlants);
    console.log(`${allPlants.length} plants inserted successfully`);

    const adminExists = await Admin.findOne({ email: 'vanshikagangwar3@gmail.com' });
    if (!adminExists) {
      await Admin.create({
        username: 'admin',
        email: 'vanshikagangwar3@gmail.com',
        password: 'admin123',
      });
      console.log('Default admin created (email: vanshikagangwar3@gmail.com, password: admin123)');
    }
    console.log('Database seeding completed!');
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
};

seedDB();
